### ISSUE TITLE
Problem Downloading the Dataset

### ISSUE THREAD

**Issue by AkhilPunia** [rodrigoberriel/satellite-crosswalk-classification#1]
Hi, 
I am currently facing problem while downloading the dataset using the script provided. 
This is the link to the[ Run Log.](https://drive.google.com/file/d/0B3iZqcitZhW5dzdSTWZWVVpMM28/view?usp=sharing)
Even though the files are being downloaded, in the operation where they have to be cropped, they are instead being deleted. I can't get my head around this problem since, I have little experience using Google APIs. 

Thanks in advance.

**Comment by rodrigoberriel** [comment]
Sorry, but I tried to reproduce this and I couldn't. Everything seems to be working for me. As you may have noticed, the images are deleted only if, somehow (see [L229](https://github.com/rodrigoberriel/satellite-crosswalk-classification/blob/b26da61a761c8de3531b95100da8cf4f2ef12d65/crosswalk_downloader.py#L229) and [L243](https://github.com/rodrigoberriel/satellite-crosswalk-classification/blob/b26da61a761c8de3531b95100da8cf4f2ef12d65/crosswalk_downloader.py#L243)), the crop fails or the cropped images cannot be saved (very unlikely). Could you please comment the line below and see if the images are saved properly and with the size `200x225` pixels? 

https://github.com/rodrigoberriel/satellite-crosswalk-classification/blob/b26da61a761c8de3531b95100da8cf4f2ef12d65/crosswalk_downloader.py#L349

**Comment by AkhilPunia** [comment]
@rodrigoberriel I checked again on my end and found out I was using the wrong API. Now, when I am using Google Static Map API, I am seeing he following error.

![screen shot 2017-09-12 at 3 24 56 pm](https://user-images.githubusercontent.com/16842872/30320470-56d5f6d6-97d0-11e7-9508-25b28f125ef9.png)

**Comment by rodrigoberriel** [comment]
@AkhilPunia This error is caused by the urllib module, not the `crosswalk-downloader.py`. If you google this error, you'll find out that there are several reasons this error can be thrown. I cannot help you further, but to say the version of the modules I'm used in two tests, both using Python 3.5 (although I tested using Python 2.7 before): `1.13.1` and `1.22`.
