### ISSUE TITLE
get api key for dataset

### ISSUE THREAD

**Issue by hansupark** [rodrigoberriel/satellite-crosswalk-classification#2]
Hi
I want to get api key for dataset. but I don't know where i get that.

how can i get api key??

**Comment by rodrigoberriel** [comment]
There is no API Key for the dataset. You might be looking for an API Key for the Google Maps Static API. In this case, you can find out how to get one here: [Get an API Key and Signature](https://developers.google.com/maps/documentation/maps-static/get-api-key).

**Comment by hansupark** [comment]
I got the api key and put it into command line but error has occured.

--> urllib.error.HTTPError: HTTP Error 403: Forbidden

In this case, Isn't the api key made well??

**Comment by rodrigoberriel** [comment]
It is hard to tell, because you did not post the full stacktrace. However, I'd guess that the problem is that you have to allow 2 services: Google Maps Static API and Directions API. You probably did only for the Google Maps Static API.

**Comment by hansupark** [comment]
Thank you! :)
